backend:
  name: github
  repo: cofoundy/portfolio-tarik-tavera
  branch: main
  base_url: https://decap-oauth-proxy-production.up.railway.app

site_url: https://tarik-tavera.cofoundy.dev

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Fecha de Publicación", name: "pubDate", widget: "datetime" }
      - { label: "Fecha de Actualización", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Imagen de Portada", name: "heroImage", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
